@startuml
title \ndocker-compose container\nstructure - production\n

!define clAuth #DodgerBlue
!define clEins #Orange
!define clZwei #68B500
!define clBlack #999999

node apache [
okieoth/d_apache2.4:0.2
--
angularauthtest_httpd_1
]
node tomcat [
okieoth/d_tomcat8_keycloak:0.1
--

angularauthtest_tomcat_1
]
node keycloak [
jboss/keycloak-postgres:2.4.0.Final
--
angularauthtest_keycloak_1
]

node db [
postgres:alpine
--
angularauthtest_db_1
]



folder httpdConf as "./httpd/conf"
folder httpdData as "./httpd/data"
folder webapps as "./tomcat/webapps"
folder db_dir as "./db"

artifact auth as "/auth"
artifact eins as "/eins"
artifact zwei as "/zwei"

auth -[clAuth]-> apache: :80
eins -[clEins]-> apache: :80
zwei -[clZwei]-> apache: :80

apache -[clEins]-> tomcat: :8080/eins
apache -[clAuth]-> keycloak: :8080/auth

keycloak -[clBlack]-> db: :5432

apache -[clBlack]right-> httpdConf
apache -[clZwei]right-> httpdData

tomcat -[clBlack]down-> webapps
db -[clBlack]down-> db_dir

@enduml